[package]
name = "roplat_rerun"
version = "0.1.2"
edition = "2024"
authors = ["Yixing <yanjizhou312@163.com>"]
readme = "README.md"
license = "Apache-2.0"
description = "Rerun integration for Robot Experimentation Platform"
categories = ["science::robotics"]
keywords = ["robot", "robotics", "rerun", "visualization", "roplat"]

[dependencies]
rerun = "0.26.0"
robot_behavior = { version = "0.6.0", git = "ssh://git@github.com/Robot-Exp-Platform/robot_behavior.git", rev = "79a3820af143a3ab75dfd3b308469482aac534c0" }
rerun_urdf = "0.1.0"
rsbullet = { version = "0.3.11", git = "ssh://git@github.com/Robot-Exp-Platform/rsbullet.git", rev = "804518bacad7fec80e065e5f95e1c34524cf8fdc" }
nalgebra = "0.34.1"
anyhow = "1.0.100"
